// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsSite.Data;

#nullable disable

namespace NewsSite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250417000000_AddNewsletterManagement")]
    partial class AddNewsletterManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6");

            // Newsletter entity configuration would go here
            // This is a simplified version - EF will generate the full version
#pragma warning restore 612, 618
        }
    }
}
